### ISSUE TITLE
[BUG] devtools::check() fails if dev folder has emacs backup files

### ISSUE THREAD

**Issue by ivokwee** [ThinkR-open/golem#1000]
**Describe the bug**
Command devtools::check() fails if dev folder has emacs backup files. Emacs produces backup file automatically of the form myfile~  and #myfile#

**Expected behavior**
Script should ignore backup files such as: myfile~  #myfile# or myfile.bak

**Screenshots**
![image](https://user-images.githubusercontent.com/19613146/224524843-51dc81a6-81e3-40ea-8d0e-6e40a32da1d0.png)
![image](https://user-images.githubusercontent.com/19613146/224524673-f2edb1e5-7d12-4161-b925-5269d69b4d09.png)

**Comment by ilyaZar** [comment]
Hi @ivokwee , I think this is an old Emacs thing and does not directly relate to golem.

But it has been ages since I used Emacs ...

So, see Dirk's post here https://stackoverflow.com/questions/1879933/r-cmd-check-complains-about-unexpected-files-in-man

You can do either of:
1. add a top-level file name `cleanup` at the root of the package
2. `R CMD --check-subdirs=no`, I do not really recall the correct value (could also be `--check-subdirs=false` but it should be one of these)

**Comment by ColinFay** [comment]
Thanks a lot @ilyaZar for the information.

As this is an issue with `devtools::check()` and not `{golem}`, I would suggest opening the issue in the `{devtools}` repository instead :) 

Closing for now
