### ISSUE TITLE
ShinyApps.io deploy error 

### ISSUE THREAD

**Issue by selwyn-mccracken** [ThinkR-open/golem#12]
hi,

I get the following error from shinyapps.io after deploying a default golem test package with rsconnect::deployApp( ) :

> An error has occurred
> The application failed to start (exited with code 1).
> 
> Loading golemdeploytest
> Error in value[[3L]](cond) : 
>   Can't call `runApp()` from within `runApp()`. If your application code contains `runApp()`, please remove it.
> Calls: local ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
> Execution halted

The app builds, runs and previews perfectly on my local machine from Rstudio.

Here is my sessioninfo:

> > sessionInfo()
> R version 3.5.1 (2018-07-02)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows 10 x64 (build 15063)
> 
> Matrix products: default
> 
> locale:
> [1] LC_COLLATE=English_New Zealand.1252  LC_CTYPE=English_New Zealand.1252    LC_MONETARY=English_New Zealand.1252
> [4] LC_NUMERIC=C                         LC_TIME=English_New Zealand.1252    
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] shiny_1.2.0                golemdeploytest_0.0.0.9000 testthat_2.0.1            
> 
> loaded via a namespace (and not attached):
>  [1] clisymbols_1.2.0     xfun_0.4             remotes_2.0.2        usethis_1.4.0        htmltools_0.3.6     
>  [6] yaml_2.2.0           rlang_0.3.1          pkgbuild_1.0.2       later_0.8.0          glue_1.3.0          
> [11] withr_2.1.2.9000     sessioninfo_1.1.1    devtools_2.0.1       htmlwidgets_1.3      memoise_1.1.0       
> [16] evaluate_0.13        knitr_1.21           yesno_0.1.0          callr_3.1.1          golem_0.0.1.0002    
> [21] BiocInstaller_1.28.0 crosstalk_1.0.0      httpuv_1.4.5.1       ps_1.3.0             Rcpp_1.0.0          
> [26] xtable_1.8-3         clipr_0.5.0          openssl_1.2.1        backports_1.1.3      promises_1.0.1      
> [31] DT_0.5               desc_1.2.0           pkgload_1.0.2        leaflet_2.0.2        jsonlite_1.6        
> [36] mime_0.6             fs_1.2.6             askpass_1.1          packrat_0.5.0        digest_0.6.18       
> [41] processx_3.2.1       gh_1.0.1             rprojroot_1.3-2      cli_1.0.1            tools_3.5.1         
> [46] magrittr_1.5         crayon_1.3.4         whisker_0.3-2        rsconnect_0.8.13     prettyunits_1.0.2   
> [51] attempt_0.2.1        assertthat_0.2.0     rmarkdown_1.11       httr_1.4.0           rstudioapi_0.9.0    
> [56] R6_2.4.0             compiler_3.5.1       git2r_0.24.0        

thanks.

**Comment by ColinFay** [comment]
Hey, 

Thanks a lot for you feedback. There is a specificity in the way Connect & shinyapps.io handle the deployment, which do not allow the `run_app` wrapper we previously suggested.

This should have been fixed through the new elements pushed in commit #ebce32 — https://github.com/ThinkR-open/golem/commit/ebce326e03e9a6343515e31a58c49f85eac49b8c

The new generated rconnect file ends with `shiny::shinyApp(ui = app_ui(), server = app_server)` instead of `run_app()` so that it can be safely deployed. That also means that if you have any external dependencies, it has to be listed in the UI, as it is done here : https://github.com/ThinkR-open/golem/blob/master/inst/shinyexample/R/app_ui.R#L6 

Could you try these two new options and let us know if it works? Seems to work here on Connect, haven't tried on shinyapps.io yet. 

Thx, 
Colin

**Comment by selwyn-mccracken** [comment]
That works wonderfully - thank you very much. 

Golem is set to be a permanent addition to our shiny app pipeline  😃 

One minor thing I noticed is that the following error gets triggered for the golem default tests on the first build run, but seems to disappear after running the app for the first time(?).

Testing golemtest
√ | OK F W S | Context
√ |  1       | test-app
x |  1 1     | golem tests

  test-golem-recommended.R:4: error: app ui
could not find function "fluidPage"
1: app_ui() at C:\Users\smccracken\Desktop\deploytest\golemtest/tests/testthat/test-golem-recommended.R:4

**Comment by ColinFay** [comment]
Hey, 

Thanks for your positive feedback, glad to read you like `{golem}`! 

The reason for this error is that for now you need to `devtools::document()` your package first in order to build your NAMESPACE (which is empty), but that might not be a perfect design choice. 

I've changed this in #44c47f0 so that the NAMESPACE of the template is not empty, and then the tests should pass with the empty template.

``` r 
> golem::use_recommended_tests()
✔ Setting active project to '/Users/colin/Seafile/documents_colin/R/lilirulirulilriu'
✔ Adding 'testthat' to Suggests field in DESCRIPTION
✔ Creating 'tests/testthat/'
✔ Writing 'tests/testthat.R'
✔ Tests added
> devtools::test()
Loading lilirulirulilriu
Testing lilirulirulilriu
✔ |  OK F W S | Context
✔ |   2       | golem tests [0.1 s]

══ Results ════════════════════════════════════════════════════════════════════════════════════════════
Duration: 0.2 s

OK:       2
Failed:   0
Warnings: 0
Skipped:  0
> 
```

**Comment by ColinFay** [comment]
Closing this one as it seems resolved. 

Feel free to reopen if needed :)
