### ISSUE TITLE
Message to link to `golem_add_external_resources()` should be conditional to the package structure

### ISSUE THREAD

**Issue by ColinFay** [ThinkR-open/golem#167]
We shouldn't get a message to put some code in `golem_add_external_resources()` if we are not inside a package structure built with `{golem}`. 

Related twitter discussion: https://twitter.com/_ColinFay/status/1178428439608659971

**Comment by novica** [comment]
I might be asking silly questions but I can't figure out how to see what happens with any changes that I make when I try to run `add_js_handler` for example.

Here I'm thinking that what is needed is a condition to test before printing the message. So, just wrap the message like this, in `add_files.R`:

```
 if (!is.null(package_name)) {
  cat_red_bullet(
    glue::glue(
      'To link to this file, go to the `golem_add_external_resources()` function in `app_ui.R` and add `tags$script(src="www/{name}.js")`'
    )
  )}
```

But I don't know how to see what this does, because if I understand correctly if I do `library(golem)` I will load the installed package and not the code I've cloned from github.

**Comment by ColinFay** [comment]
So the idea behind this one is that if you are using golem outside a golem app, for example in the default app.R example from RStudio, you'll get this message in your console `To link to this file,  go to the `golem_add_external_resources()` function in `app_ui.R` and add `tags$script(src="www/plop.js")` 

The idea is that we should receive this message only if we are in a golem package. The best way to do that I guess would be to detect if the current working directory contains a DESCRIPTION file. 

Concerning the question about testing, the best way is to implement changes and to install the package (through the Build tab in RStudio for example), and then to try if again :)
