### ISSUE TITLE
couldn't find google_analytics.js from www/

### ISSUE THREAD

**Issue by cparsania** [ThinkR-open/golem#168]
Hi, I build shiny app using `golem`. Followed instructions as given in `(01/02/03)_dev.r`. all went well. I successfully build .tar.gz file as well. 

The problem arises when i install the package using `devtools::install()` or `devtools::install_local()`. when i run the app using `run_app()` function, it says `cannot open file 'www/google_analytics.js': No such file or directory`  this is how i included js  inside my app.  `tags$head(includeScript("www/google_analytics.js"))`

**Comment by cparsania** [comment]
I figured it out. Here is the catch. I forgot to put `tags$head(includeScript("www/google_analytics.js"))` inside `golem_add_external_resources()`. Once I did, it resolved the problem.

**Comment by cparsania** [comment]
Similar to above, i have included some plain HTML in my shinyApp using `includeHTML`. Where should i keep these HTML files ?

**Comment by ColinFay** [comment]
Hey @cparsania, 

The current issue is that the basic shiny app format "hides" the two ways to include elements in your application. In the standard www/, you're referring to the same folder, but which are used in two different states. 

+ `addResourcePath()` adds a link __available at runtime__, i.e while your app is served in your browser. That's why when you do `tags$script(src="www/handlers.js")` : this piece of HTML is read at app runtime, which has access to `www/` as a mounter folder. 

+ If you want to add to your app elements which are needed __at compile time__, as what `includeMarkdown` or `includeHTML` does, you'll need to specify the path relative to your app package, in the form of `system.file("app/www/plop.md", package = "golemexample")`. 

Please check https://github.com/ColinFay/golemexample#using-shinyincludexxx and let me know if this helps. 

Cheers, 
C.

**Comment by cparsania** [comment]
Thanks, Colin for making me think of how `system.file()`actually work in backend. Also, `[golemexample](https://github.com/ColinFay/golemexample/blob/master/dev/02_dev.R#L28)` is useful resource to get rid of many other issues. So, it solved my problem. Cheers, ~Chirag.

**Comment by ColinFay** [comment]
Perfect :) 

Closing the issue then
