### ISSUE TITLE
Remotes elements should be put into the Dockerfile 

### ISSUE THREAD

**Issue by ColinFay** [ThinkR-open/golem#22]
By default, `{golem}` is used as a dependency to the created app. 

But the `add_dockerfile()` function only parses the Imports from DESCRIPTION, so doesn't install Remotes elements

**Comment by ColinFay** [comment]
Handled by using `install_local()` on `app.tar.gz`

**Comment by aftonsteps** [comment]
Sorry if this is a silly question, but how would you use `install_local()` in this case? I can see how to locally include a tar.gz for some library along with the app's other local files, and then use `install_local()` somewhere in the app's code to install from that tar.gz. But I think think this would install that library every time that app starts up, rather than just once when the container is created. Is there a way to specify installation from the tar.gz somewhere in the Dockerfile?
