### ISSUE TITLE
Error: (converted from warning) package ‘golem’ is not available (for R version 3.5.3)

### ISSUE THREAD

**Issue by kuty-kajot** [ThinkR-open/golem#255]
Hi. When building a Dockerfile for golemized shiny app it stops at:
`
remotes::install_cran("golem")
Installing 1 packages: golem
Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
Error: (converted from warning) package ‘golem’ is not available (for R version 3.5.3)
Execution halted
The command '/bin/sh -c R -e 'remotes::install_cran("golem")'' returned a non-zero code: 1
`
Using remotes::install_cran("golem") in Rstudio results in successful package installation. Whatcould be the problem? I am using win10 for local app deployment & testing before going on server.

**Comment by ColinFay** [comment]
When using a Dockerfile based on `rocker/r-ver:3.5.3`, you'll get a repo fixed on a MRAN date. 

MRAN are snapshots of the CRAN on a specific day. The 3.5.3. docker image is compiled with a specific date of this snapshot, which will not contain golem as it was released after this date. 

This will be fixed by the newer version of golem (soon to be released) which no longer uses this snapshot date. 

https://github.com/ThinkR-open/golem/blob/dev/R/add_deploy_helpers.R#L320 

Sorry for the inconvenience.

**Comment by kuty-kajot** [comment]
Changing to `remotes::install_github("Thinkr-open/golem")` solves the problem.

**Comment by kuty-kajot** [comment]
Thanks for the quick reply Colin. It does not seem to be much of a problem. Great package!

**Comment by VincentGuyader** [comment]
@kuty-kajot have a lot to the `dev` branche, the new `add_dockerfile` function is better about this.

Regards

**Comment by ColinFay** [comment]
Solved, so closing now
