### ISSUE TITLE
Add possibilityt to specify proxy in the dockerfile creation tools

### ISSUE THREAD

**Issue by Nabzoouu** [ThinkR-open/golem#266]
the goal is to have this kind of Dockerfile :

```
FROM rocker/r-ver:3.6.1
RUN apt-get update && apt-get install -y  gdal-bin git-core libcurl4-openssl-dev libgdal-dev libgeos-dev libgeos++-dev libpng-dev libpq-dev libproj-dev libssh2-1-dev libssl-dev libxml2-dev make pandoc pandoc-citeproc zlib1g-dev
RUN echo "options(repos = c(CRAN = 'https://cran.rstudio.com/'), download.file.method = 'libcurl')" >> /usr/local/lib/R/etc/Rprofile.site
RUN echo "Sys.setenv(http_proxy= 'xxx:3128/');Sys.setenv(https_proxy= 'http://xxx:3128/');Sys.setenv(HTTP_PROXY= 'xxx:3128/');Sys.setenv(HTTPs_PROXY= 'xxx:3128/')">> /usr/local/lib/R/etc/Rprofile.site
```

**Comment by ColinFay** [comment]
Hey, 

Thanks for the idea 💪

I think the smart way to do this would be to have a parameter that allows to pass environment variables, regardless of the content. So something like: 

```r
add_dockerfile(..., env_var = c(x = "y", z = "plop")
```

Which would create: 

```r 
RUN echo "Sys.setenv(x= 'y');Sys.setenv(z= 'plop/')">> /usr/local/lib/R/etc/Rprofile.site
```

So that it's virtually possible to add any env var, not just the one for proxy, and wouldn't pollute with endless parameters to the function :)

**Comment by cderv** [comment]
Just curious @Nabzoouu : 

why not pass the proxy environment variable at run time 
```sh
docker run -e HTTP_PROXY=xxx:3128 
```
or build time 
```sh
docker build --build-args HTTP_PROXY=xxx:3128
```

or even using `docker-compose` to build and run the docker images ? 

This feels like the kind of information that should not be in a dockerfile because it is dependant on where the images in run. 🤔

**Comment by ColinFay** [comment]
Hey, 

Small update on that, now that the dockerfile can be manipulated programmatically with `{dockerfiler}` (see #493), modifications to the Dockerfile can be performed post creation :) 

I'm closing for now, feel free to comment below if you want it to be reopen
