### ISSUE TITLE
add_dockerfile should be able to create a Dockerfile which can build the golem from sources

### ISSUE THREAD

**Issue by VincentGuyader** [ThinkR-open/golem#269]
for example like  this :  

```
FROM rocker/r-ver:3.5.1
RUN echo "options(repos = c(CRAN = 'https://cran.rstudio.com/'), download.file.method = 'libcurl')" >> /usr/local/lib/R/etc/Rprofile.site
RUN R -e 'install.packages("remotes")'
RUN R -e 'remotes::install_github("r-lib/remotes", ref = "97bbf81")'
#COPY aefff_*.tar.gz /app.tar.gz
#RUN R -e 'remotes::install_local("/app.tar.gz")'
RUN mkdir /build_zone
ADD . /build_zone
RUN R -e 'setwd("/build_zone");devtools::build(path = ".")'
RUN R -e 'setwd("/build_zone");remotes::install_local()'
EXPOSE 80
CMD R -e "options('shiny.port'=80,shiny.host='0.0.0.0');aefff::run_app()"
```

**Comment by ColinFay** [comment]
Is the idea to have the source pkg in `/build_zone`? 

As far as I see it we should default to this behaviour: copy the source app folder inside the docker and use install_local("folder") instead of relying on the tar.gz. 

Using the tar.gz adds a little bit of complexity bcs : 
- You need to either `devtools::build()` and copy and paste the tar.gz next to the Dockerfile, so either the dockerfile has to be at "../", either you build the tar.gz inside `devtools::build(path = ".")`, but you have a tar.gz inside your source package
- When updating a version, you currently have to manually remove the tar.gz of the older version, as `aefff_*.tar.gz` matches multiple arguments. 

So I think we should have something like : 

```
FROM rocker/r-ver:3.5.1
RUN echo "options(repos = c(CRAN = 'https://cran.rstudio.com/'), download.file.method = 'libcurl')" >> /usr/local/lib/R/etc/Rprofile.site
RUN R -e 'install.packages("remotes")'
RUN R -e 'remotes::install_github("r-lib/remotes", ref = "97bbf81")'
COPY . /build_zone
RUN R -e 'setwd("/build_zone");remotes::install_local()' 
...
```

That way, we don't have to use the tar.gz at all. Makes it easier to handle on the long run. 

Is there a reason for sticking with the tar.gz ?

**Comment by VincentGuyader** [comment]
>Is there a reason for sticking with the tar.gz ?

its's easier to give someone a `tar.gz` file and and Dockerfile, than a folder containing a Dockerfile and a lot of other file :)

**Comment by ColinFay** [comment]
Well, strictly speaking it's easier to bundle the dockerfile + the folder inside on tar 😎🙊

trolling aside, I think it's no good practice to invite users to create the Dockerfile inside the pkg root, as it will also implies that one need put the targz there, leading to a pkg tar inside itself, which is weird. 

Also 

add_dockerfile();devtools::build()

Exports in different folders, so if we want both to work together we have to 

add_dockerfile();devtools::build(path =".")

Also, I don't think we should ask the user to build the targz manually: that might lead to "I forgot to update but I still have the late version of the targz so it compiled without me noticing that I made a mistake" kind of situation, + when you have two targz with two versions, the dockerfile doesn't compile. 

What about adding a "dockerexport" folder at the root of the source app, which is automatically clean and rebuilt with the dockerfile + the targz? 

That would prevent the mess of dealing with things going to ../ with devtools::build, prevent from having the dockerfile in the pkg source and/or the targz. 

Would also make it easier to share the content, as "dockerexport" would be shareable and clearly identified.
