### ISSUE TITLE
Switch path and file creation to fs

### ISSUE THREAD

**Issue by ColinFay** [ThinkR-open/golem#285]
paths and files creation should be done based on `{fs}`

**Comment by cderv** [comment]
Take care of the change of definition for `home` in R depending on the OS.
TL;DR `~` in fs 📦  on windows does not mean the same thing as base R. 
You may already know about that.

Otherwise: 

* This is explained in help page: https://fs.r-lib.org/reference/path_expand.html#details

* This can be tricky. With usethis, the default is `fs` definition and this can be tricky sometimes. I need to use `path_expand_r` or `path_home_r` to define path from R base home definition 

Cheers!
