### ISSUE TITLE
Should we handle npm install? 

### ISSUE THREAD

**Issue by ColinFay** [ThinkR-open/golem#296]
I wonder if we should handle npm installs inside golem so that the js and css files go to the right place

**Comment by cderv** [comment]
As a user in a company, I share my 2 cents here. The more golem feature will be integrated with other type of software / tools (like docker, npm, ...) the more difficult it will be to use. I am in favor of several options of usage instead of default features integrated deeply with other tools.

I am curious where this will be headed though... 

Cheers.

**Comment by ColinFay** [comment]
Yeah I wasn't sure how to handle that but you're right that we shouldn't handle `npm` itself, yet it would be nice to have a way to set a skeleton for receiving the npm modules. 

This idea is born from the fact that if you currently do npm install it will add the node_modules at the root of the package and then it has to be manually moved to inst/app/www. 

I was thinking of something like `golem::use_npm()` which would set some kind of skeleton so that when we later do `npm install` from the command line, the modules would be installed at the right spot.

**Comment by cderv** [comment]
> I was thinking of something like golem::use_npm() which would set some kind of skeleton so that when we later do npm install from the command line, the modules would be installed at the right spot.

Seems like a real helper function that is just of use for those using npm. 👍

I am thinking of some options but not sure how npm is working and what skeleton means really.  So I’ll look into it before saying anything else.

**Comment by ColinFay** [comment]
Closing for now, I don't think this should be done by golem for now
