### ISSUE TITLE
accessing data in golem shiny app

### ISSUE THREAD

**Issue by novica** [ThinkR-open/golem#413]
I have a golem shiny app that reads from a dataset and returns a table.

So in the `ui` I have `tableOutput(outputId = "head")`, and in the server I have 

``` 
dataset <- head(x)
output$head <- renderTable({ dataset }) 
```  
where `x` is the `iris` dataset stored in the `data` folder with `usethis::use_data`.

I am installing it with `devtools::install()`. When I do `myapp::run_app()` I get an error:
```
Listening on http://127.0.0.1:5108
Warning: Error in head: object 'x' not found
  53: head
  52: server
Error in head(x) : object 'x' not found
```
When I change the line 
`dataset <- head(x)`
to
`dataset <- head(myapp::x)` and reinstall `myapp::run_app()` runs successfully.

Again, I am not sure if maybe I am doing something wrong with the golem setup, or this is how it is supposed to be.

**Comment by ColinFay** [comment]
Hey, 

Thanks for reporting. 

Yes, this is not an issue with golem itself but with R packages. 

I've written a reprex here: https://github.com/ColinFay/datapackagewithoutexplicitnamespacing 

The TLDR is: add explicit namespacing `pkg::dataset` to your dataset, because `pkg::function()` doesn't have access to the dataset before you `library()` it.

**Comment by moodymudskipper** [comment]
Hey Colin I think it's because datasets under data/ are not stored in the package's namespace but in the lazydata env.
When calling library you make them visible because they're copied in the package env on the search path, this is brittle however if you use data from the package, because the global environment could override those.

I believe defining a dataset as internal should solve this problem more robustly, see Hadley's take there: https://r-pkgs.org/data.html#sec-data-sysdata
