### ISSUE TITLE
Docker image rebuild time

### ISSUE THREAD

**Issue by robertoromor** [ThinkR-open/golem#456]
I dont know if this is a fundamental issue of combining shiny, package building and docker but it takes a lot of time rebuilding and I want to know if I am doing something wrong in my dockerfile, maybe the ordering of the  docker commands.
It is taking a lot of time to add small features and see them implemented in the deployed app because if docker image rebuild times, do you guys know a workaround or can point to what I am doing wrong. Attached you will find the dockerfile
 
[dockerfile_roberto_romo.txt](https://github.com/ThinkR-open/golem/files/4806337/dockerfile_roberto_romo.txt)

**Comment by VincentGuyader** [comment]
Hi,

it's look likes a cache issue with your docker, once you did one compilation you dont need to restart from the beginning.

you may need to use 2 Docker file the first like this :

```
FROM rocker/r-ver:3.6.1
RUN ...
RUN ...
```

then you create an image with `docker built . -t baseimage`

and another Dockerfile with

```
from baseimage
COPY ...
```

does it make sens for you ?

regards

**Comment by robertoromor** [comment]
Yes, I will try doing that. Thanks

**Comment by ColinFay** [comment]
Hey, 

Thanks for your report!

Another solution (on top of the one Vincent wrote) if you want to fasten the package installation: there is now a public RStudio package manager that contains pre-compiled packages, making Dockerfile compilation faster. 

Learn more at: https://blog.rstudio.com/2020/07/01/announcing-public-package-manager/

Closing for now, feel free to comment if you encounter any issue.

**Comment by chintanp** [comment]
I think one of the reasons the docker build is slow is for me, is that the new dependencies go to the top instead of the bottom. For example, if I add a new package dependency say glue like so, `usethis::usepackage('glue')`, then the install line in Dockerfile `RUN Rscript -e 'remotes::install_version("glue",upgrade="never", version = "1.4.2")'` goes to the top of all `RUN Rscript...`  instead of the bottom. And this invalidates the rest of the Dockerfile, so all the layers for package installs are repeated. Any particular motivation for installing the new package before others?
