### ISSUE TITLE
Problem using Shiny.onInputChange in module

### ISSUE THREAD

**Issue by AMillanFL** [ThinkR-open/golem#481]
Hello,

I need to get return of user clic on a link in my golem app and I try to do it with js/R.
Here my structure : 
In my module mod_test.R
```
mod_test_ui <- function(id){
  ns <- NS(id)
  tagList(
    mainPanel(
      checkboxInput(ns("check"), "Test")
    ),
    sidebarPanel(
      htmlOutput(ns("legend"))
    )
  )
}

mod_test_server <- function(input, output, session, lamp_datas, coord){

  observeEvent(input$filtreClic, {
    updateCheckboxInput(session, "check", value = !input[["check"]])
  })
  
  output$legend <- renderUI(HTML( a("test clic", class = "", onclick = "interactiveLegend(1);") ) )
}
```

And my script.js : 
```
 function interactiveLegend(id) {
  console.log(id);
  Shiny.onInputChange("filtreClic", id);
}
```

When I clic on the link, I can see the id displayed in the browser console by nothing changes in R, the checkbox stay dead.
I get no js error.
Is there a specific input call to make react the observeEvent with Golem ?

Thanks

Arnaud

**Comment by ColinFay** [comment]
Hey, 

That's not linked to `{golem}` but to the fact that you need to pass the __full__ id to the JavaScript function. 

In other words, in your example, the __actual__ id at runtime is the result of ns("check"): 

``` r 
id <- "mod_ui_1"
ns <- NS(id)
ns("check")
[1] "mod_ui_1-check"
```

which is the actual id observed in the server, even if it's transparent to you (in the server side of the module, you write output$chek, but what Shiny is actually doing is watching for output$mod_ui_1-check).

So if you want your JS to set the input, you need to set the input __fully namespaced__. 

I suggest writing your JavaScript function this way: 

```
function interactiveLegend(shinyid) {
	const value = "something"
	Shiny.onInputChange(shinyid, value);
}
```

So that it can be called using the namespaced id from R. 

Here is a working example: 

```r
nameui <- function(id){
  ns <- NS(id)
  tagList(
    tags$button(
      "plop", 
      onclick = sprintf(
        "Shiny.setInputValue('%s', Math.random())", 
        ns("my_namespaced_id")
      )
    )
    )
  }

name <- function(input, output, session){
  
  observeEvent( input$my_namespaced_id , {
    print(input$my_namespaced_id)
  })
  
}

library(shiny)
ui <- function(request){
  tagList(
    nameui("nameui")
  )
}

server <- function(
  input, 
  output, 
  session
){
  callModule(name, "nameui")
}

shinyApp(ui, server)
```

**Comment by AMillanFL** [comment]
That's it ! Thanks !

Every input called from a module is automaticaly prefix with the module_id. I would have think about it.
