### ISSUE TITLE
shinyapps deployment issues - RStudio recommended I open ticket

### ISSUE THREAD

**Issue by sjspielman** [ThinkR-open/golem#534]
Hi golem team, 

I have an app which I have built in your framework which has been working wonderfully, and so well-organized! I have been keeping the app live and deployed on shinyapps using the provided `app.R` file for deployment generated by golem::add_shinyappsio_file() as:

```
# Launch the ShinyApp (Do not remove this comment)
# To deploy, run: rsconnect::deployApp()
# Or use the blue button on top of this file

pkgload::load_all(export_all = FALSE,helpers = FALSE,attach_testthat = FALSE)
options( "golem.app.prod" = TRUE)
dragon::run_app() 
```

However, a recent deployment has led to some significant problems such that the app no longer loads on shinyapps, with a persistent error about not finding `%>%`, suggesting `dplyr` isn't loaded. This has never been an issue with shinyapps in the past; loading the package (DESCRIPTION, NAMESPACE, etc) is sufficient to load the libraries and one does not need library(dplyr).

This issue has had the RStudio shinyapps support team stumped for about a week now and they aren't able to figure it out. They have suggested that `load_all()` should never be used when deploying, but given the golem app structure, I see no other way to work this issue.

The app in question is here: http://github.com/sjspielman/dragon

One question I asked the RStudio team was about the RStudiu GUI when deploying - the interface now has you specifically choose which files in the directory should be deployed. I wonder if there is a better recommendation for which files to specifically include in the bundle to shinyapps deployment? I have seen the outputted lined "Note that you'll need to upload the whole package to ShinyApps.io" from `golem::add_shinyappsio_file()` so I have indeed been including all files. Is this correct?

Thanks, 
Stephanie

**Comment by VincentGuyader** [comment]
What if you try with `devtools::load_all()` instead of `pkgload::load_all()` ?

**Comment by aronatkins** [comment]
@VincentGuyader - `devtools::load_all` is essentially just a call to `pkgload::load_all`.

**Comment by aronatkins** [comment]
@sjspielman - I see `%>%` issues when running the dragon application in a clean R session (one that has not loaded `dplyr` or `magrittr`). This happens in my local environment before deploying to shinyapps.io.

I can successfully run the application and deploy to shinyapps.io after rewriting the palette variables into functions (and then updating the code that references those variables).

**Comment by sjspielman** [comment]
Hi @aronatkins, this is really interesting!! I had actually been *removing* that whole `inst/` subdirectory when deploying to shinyapps, but it seems I missed some cases where %>% wasn't visible. 

I also can confirm I CAN run the package in a clean R local session without loading any libraries. I'm R 4.0.2 (starting to think I should have stayed at 3.6!). Are you as well?

**Comment by ColinFay** [comment]
Hey folks,

I've solved the bug before leaving the office today but haven't had time to publish here. 

Will do tonight. 

Colin

**Comment by sjspielman** [comment]
An aside, I am so grateful for all of your feedback here. I VERY VERY VERY MUCH appreciate your time and help!!!!!!!

**Comment by sjspielman** [comment]
Hi all, 

Re-wrote the semi-embarrassing code into a function, and we have successful deployment. THANK YOU SO MUCH again for finding what my eyeballs were too tired to see.

Have a wonderful evening!!

-Stephanie

**Comment by aronatkins** [comment]
@sjspielman I was testing with R 3.6.3. I had not considered R version as part of the equation.

**Comment by ColinFay** [comment]
Hey Stephanie, 

Thanks for the nice words, happy to hear you like `{golem}` 😁

I've started writing this answer before leaving work today and in the meantime you found the answer 💪

Let me dig a little bit more in what happened so that might also be useful for future developers!

`load_all()` behaving like a `library()` call, there is no issue with using it for the deployment, it's as secure (I'd even say more secure but I'm biased ;) ) as doing a series of `source()`, which is by the way the default behavior since `{shiny}` 1.5. So there is no problem with it, at least that I'm aware of :) 

The source of your bug was the following: 

You've declared a code in `utils_palette.R` that defines an object.
In an R package, all assignments are evaluated at package namespace build time, but without the dependencies being loaded. In other words, when you try to launch a package with `load_all()`, all the assignments are performed (functions and objects are created) in the R/ scripts without launching the packages listed as dependencies. This environment without dependencies launched is not an issue with function because body of functions are lazily evaluated at assignment time, and only resolved at run time: 

```r
# You can define this function
this <- function(){
    afunctionthatdoesnotexist()
}

# But you can't run it
this()
Error in afunctionthatdoesnotexist() : 
  could not find function "afunctionthatdoesnotexist"

# But you can't do that, object assignment is not lazily evaluated
that <- afunctionthatdoesnotexist()
Error in afunctionthatdoesnotexist() : 
  could not find function "afunctionthatdoesnotexist"
```

The `utils_palette.R` from your app contains an object definition (case number two of my example), which is done with a `%>%. At package build time, `{magrittr}`, hence the object definition fail to work. 

Solutions: 

+ Define everything as a function, so that body is lazily evaluated at build time, and call this function after app launch to have access to the value
+ If it's an object that is not subject to change, define it as a package dataset 

Hope this helps 🤘

Colin

**Comment by sjspielman** [comment]
Hi @ColinFay, 

Indeed I **love** golem!! It has really helped me organize the shiny app into a proper package (that is when I remember to write functions...). Thanks for all your efforts on the framework.
 
I ended up moving the code to create data stashed in sysdata.R, so it's just cooked in a dataset now. Honestly I'm just really fascinated that this code has been working _at all_ before now! Oh well, onwards and upwards :)

-Stephanie
