### ISSUE TITLE
how to include multiple authors with the fill_desc function 

### ISSUE THREAD

**Issue by jennahamlin** [ThinkR-open/golem#609]
Hello -

It is unclear to me how to specify multiple authors with the fill_desc function as I want to provide credits and links to those that helped develop my R shiny package for when I use pkgdown. 

I see in the [R packages link](https://r-pkgs.org/description.html); that you can specify multiple authors, but I don't see how to port that information over into the description by the fill_desc function. Is it possible? 

Thank you :)

**Comment by ColinFay** [comment]
Hey @jennahamlin, 

That's indeed a very legit need, we've been tracking this in this issue already : https://github.com/ThinkR-open/golem/issues/256

I'm torn between adding this straight into `fill_desc` of PR-ing directly this into `{desc}` — the first will be a quick fix, the second more efficient :) 

Thanks for opening this issue — that proves that there is a desire to have this natively supported. 
I'm closing this issue for now — not because it's not relevant (it is relevant) but just so that we can keep track of this question at one place (in #256 :) ). 

Cheers, 
Colin
