### ISSUE TITLE
warning message

### ISSUE THREAD

**Issue by lijian007** [ThinkR-open/golem#650]
When the package is pushed to rstudio connect, the system shows a message:
 "Loading R/ subdirectory for Shiny application, but this directory appears to contain an R package. Sourcing files in R/ may cause unexpected behavior"

Is a way to avoid sourcing the files in /R subdirectory?

**Comment by ColinFay** [comment]
Hey, 

Yes, this is unfortunately something native in `{shiny}` since v 1.5.0. 

You can remove this warning by setting `options(shiny.autoload.r=FALSE)` inside an `.Rprofile` file. 

```r
write("options(shiny.autoload.r=FALSE)", ".Rprofile")
```

Let me know if that fixes. 

For more info:

https://shiny.rstudio.com/reference/shiny/1.6.0/loadSupport.html

And a discussion about this here:

https://github.com/ThinkR-open/golem/issues/468#issue-650876168

Cheers, 

Colin

**Comment by lijian007** [comment]
Thanks Colin, I read up #468. Can we just add a rm(list=ls()) in app.R to remove the side effects of sourcing /R?

**Comment by ColinFay** [comment]
@lijian007 as far as I can tell, the sourcing of the R/ folder doesn't create anything inside the environment. 

```r
> shiny::runApp()
Warning in loadSupport(appDir, renv = sharedEnv, globalrenv = NULL) :
  Loading R/ subdirectory for Shiny application, but this directory appears to contain an R package. Sourcing files in R/ may cause unexpected behavior.
Loading ccc

Listening on http://127.0.0.1:5527


> ls()
character(0)
```

Does it create anything in yours?

Cheers, 
Colin

**Comment by ColinFay** [comment]
Closing for lack of additional information :) 

Feel free to reopen if you still see this issue. 

Thanks again for reporting this ! 

Cheers, 
Colin
