### ISSUE TITLE
ui & server params for run_dev function

### ISSUE THREAD

**Issue by mark-druffel** [ThinkR-open/golem#728]
Thank you so much for golem, this package is fantastic! 

This seems to be the same issue as https://github.com/ThinkR-open/golem/issues/39, but the proposal maybe a bit different. Sorry for the length of the writeup, I tried to explain in great detail because I'm new to golem and may just not be using it to it's fullest extent. Let me know your thoughts and thanks for your time!

## Background
I am building a dashboard using bs4Dash and as the app is growing in the number of modules, adding new functionality is become more challenging. When adding new modules, I often have to restructure the ui and server just to debug the new module until I can get it working. It's gotten to the point that I found myself using a blank version of the dashboard just to write the module. I wrote the two functions below and just add the new modules to this to test until I have it working:

```
dummy_ui <- function(request) {
  tagList(
    golem_add_external_resources(),
    bs4Dash::dashboardPage( 
      header = bs4Dash::bs4DashNavbar(),
      sidebar = bs4Dash::dashboardSidebar(), 
      body = bs4Dash::dashboardBody(),
      controlbar = bs4Dash::dashboardControlbar()
    )
  )
}

dummy_server <- function( input, output, session ) {
}
```

Once I have the modules working in the above, I add them to `app_ui` and `app_server`. If there's a better way to do this in the golem workflow please let me know - I'm pretty new to the package and only read through the book once so far.

## Problem
I can't use `dummy_ui` and `dummy_server` with `golem::run_dev` as it's currently written because there are no parameters. To allow myself to work around this and keep using the `run_dev` workflow I've just added some code to my `run_dev` file in the package and added a param to `run_app`. 

~/dev/run_dev.R
```
# Set options here
options(golem.app.prod = FALSE) # TRUE = production mode, FALSE = development mode

# Comment this if you don't want the app to be served on a random port
options(shiny.port = httpuv::randomPort()) 

# Detach all loaded packages and clean your environment
golem::detach_all_attached()
# rm(list=ls(all.names = TRUE))

# Document and reload your package
golem::document_and_reload()

# Run the application
run_app(dummy = Sys.getenv("RUN_GOLEM_DUMMY"))

```

~/R/run_app.R
```
run_app <- function(
  dummy = "FALSE",
  onStart = NULL,
  options = list(), 
  enableBookmarking = NULL,
  uiPattern = "/",
  ...
) {
  with_golem_options(
    app = shinyApp(
      ui = switch((dummy == "TRUE") + 1, app_ui, dummy_ui),
      server = switch((dummy == "TRUE") + 1, app_server, dummy_server),
      onStart = onStart,
      options = options, 
      enableBookmarking = enableBookmarking, 
      uiPattern = uiPattern
    ), 
    golem_opts = list(...)
  )
}
```

I then use withr to run `golem::run_dev`. It's pretty janky but it works.
```
withr::with_envvar(new = c("RUN_GOLEM_DUMMY" = "TRUE"), 
                   golem::run_dev()
                   )
```

## Possible Solution
If I'm using golem properly and this seems like a rational problem, could parameters be added to `golem::run_dev` to call ui and server directly? Happy to take a stab a PR myself if so.

**Comment by ColinFay** [comment]
Hey @mark-druffel 

This is a pretty valid need, and one we have raised several times in the `{golem}` team already :) 

This is def something I'd love to see happening. 
My big "developer fear" right now is that it's  kind of hard to create something generic enough that will work in most cases. 
The reason is that most modules will take parameters, and possibly values passed downward from other top level modules. 

Right now the run_dev() function works almost every time, and chances are you rarely change the parameters to run_app() so it's fine. 

But for example, one module can take one, two, three reactiveValues, it can take a reactive(), it can take a character argument, etc... 

See for example: 

+ https://github.com/ColinFay/golemexamples/blob/master/golemR6/R/mod_a.R#L26 takes an R6 object
+ https://github.com/ColinFay/golemexamples/blob/master/golemwhereamidemo/R/mod_name_of_module1.R#L20 takes a reactiveValue
+ etc.

I'd love to find a way to make this happen, but I'm not sure how to implement a generic enough solution, and this was my concern with #39. 

I'll need to think of something that can work, and I'm open to any suggestion if you have any :)

**Comment by ColinFay** [comment]
And for example one module might depends from another, as described in https://engineering-shiny.org/structuring-project.html#a.-returning-values-from-the-module, making it harder to build a separate run_dev for each :(

**Comment by mark-druffel** [comment]
Sorry for the delayed response, I didn't realize the complexities with this work or that this already had an issue. Probably makes sense for me to close this issue since #39 already covers it?

I don't know golem well enough to make suggestions, but as I continue to learn the library I'll keep it in mind and comment on #39 if I have any ideas! Thanks for your response and your amazing work on this library :)
