### ISSUE TITLE
replace usethis::use_package with attachment::att_amend_desc() in 02_dev.R

### ISSUE THREAD

**Issue by VincentGuyader** [ThinkR-open/golem#784]
because `attachment::att_amend_desc` is cool :)

**Comment by ColinFay** [comment]
My issues right now are: 
- We tend to aim for less dependencies, not more

- If I do attachment::att_amend_desc() inside `golem`, it output an incorrect change to DESCRIPTION: 

```r
> attachment::att_amend_desc()
Updating golem documentation
i Loading golem
Writing NAMESPACE
Warning: Link to unknown topic in inherited text: tools::print.via.format
Writing NAMESPACE
[+] 4 package(s) added: pkg, s, sass, i.
```

+ `pkg::` is in the documentation, there should be no reason for this to be added
+ `"%s:::app_server"` comes from `sprintf("%s:::app_server",pkg)` at https://github.com/ThinkR-open/golem/blob/dev/R/add_files.R#L643, which is also incorrect
+ `sass::` is what is written in the sass files, it is a package but this shouldn't be added as an `Imports` 
+ I don't know where `i` comes from  ¯\_(ツ)_/¯ 

It will also move a bunch of package : 

- `{dockerfiler}` moves to Imports where we deliberately chose to have it as a Suggest, because of https://github.com/ThinkR-open/golem/blob/dev/R/add_dockerfiles.R#L74 / https://github.com/ThinkR-open/golem/blob/dev/R/add_dockerfiles.R#L81. Same for `{rlang}`, and `{testthat}`.
- `{glue}` is moved to Imports, it should stay in suggest (vignette only)
- `{pkgbuild}`  is moved to Imports, it should stay in suggest because of https://github.com/ThinkR-open/golem/blob/dev/R/add_dockerfiles.R#L291. Same with `{rsconnect}` and https://github.com/ThinkR-open/golem/blob/dev/R/add_rstudio_files.R#L33
- `{processx}` is `skip_if_not_installed()`, so it shouldn't be moved to the Import https://github.com/ThinkR-open/golem/blob/dev/R/test_helpers.R#L75

So as long as the tool is not fully reliable, I'm not sure I want to promote it as a magic tool, even more in a production context where we would want to be able to lower the number of dependencies inside your deployed app: so for example, there is no reason to have in Imports the packages from the test suite.

**Comment by statnmap** [comment]
You can do
```r
attachment::att_amend_desc(
   pkg_ignore = c("pkg", "s", "sass", "i", "dockerfiler", "pkgbuild", "rsconnect", "processx"),
   extra.suggests = c("dockerfiler", "pkgbuild", "rsconnect", "processx")
)
```
- If {glue} is in Imports, it means it is used somewhere in a "R/" file. Dependencies in vignette are added in Suggests.
