### ISSUE TITLE
Where to place global variable in golem?

### ISSUE THREAD

**Issue by YonghuiDong** [ThinkR-open/golem#965]
Hi golem devilment team,

I am in the process of converting my current ShinyApp under golem frame. 

In my app, I  have a global variable, which allows users to modify the data during data processing.

It was defined in a R file named `global.R`

```r
sfData <- reactiveValues(data = NULL, group = NULL, filter = NULL, clean = NULL)
```
Then I included it in my shiny server file like this:
```r
shinyServer(function(input, output) {
  source("global.R", local = FALSE)
  source("server-uploadData.R", local = TRUE)
  source("server-preprocessData.R", local = TRUE)
  source("server-viewResult.R", local = TRUE)
  source("server-downloadReport.R", local = TRUE)
  
onStop(function(){
    rm(sfData, envir = .GlobalEnv)
    gc()
  })
})
```

The App worked quite well. I am wondering how can I do this under golem frame work?

Thanks a lot for your help.

Dong

**Comment by ALanguillaume** [comment]
Hi @YonghuiDong ,

Just define it in your `app_server()` in `R/app_server.R`.

``` r
#' The application server-side
#'
#' @param input,output,session Internal parameters for {shiny}.
#'     DO NOT REMOVE.
#' @import shiny
#' @noRd
app_server <- function(input, output, session) {
  global <- reactiveValues(
    data = NULL,
    group = NULL, 
    filter = NULL, 
   clean = NULL
    )
  )
```
To know how to harness the full power of `{golem}` I will recommend you to have a look at the book: https://engineering-shiny.org

Your particular question is addressed in Chapter 3 https://engineering-shiny.org/structuring-project.html?q=petit#b.-the-strat%C3%A9gie-du-petit-r

The logic of the chapter remains valid but our practice as evolved a bit. The "stratégie du petit r" as morphed into the strategy of the global messenger. We  now tend to define a global reactiveValues called `global` instead of `r`.
The principle remains the same though. This global reactiveValues is passed around modules as a parameter to allow the data to flow within the app.

**Comment by YonghuiDong** [comment]
Dear @ALanguillaume,

Thanks a lot for your kind help and suggestion! I will go through this nice book.

Best,

Dong
